/**
 * Generates src/generated/frontendAssets.ts, which imports every file of the
 * frontend build with `{ type: "file" }`. `bun build --compile` then embeds
 * those files in the executable, and `bun run` resolves them to paths on disk.
 *
 * If the frontend has not been built, the manifest is empty and the server
 * only provides the game server API.
 */
import { Glob } from "bun";
import { mkdir } from "fs/promises";
import { join, relative } from "path";

const backendDir = join(import.meta.dir, "..");
const buildDir = join(backendDir, "..", "build");
const outDir = join(backendDir, "src", "generated");
const outFile = join(outDir, "frontendAssets.ts");

const files: string[] = [];
if (await Bun.file(join(buildDir, "index.html")).exists()) {
  for await (const file of new Glob("**/*").scan({ cwd: buildDir })) {
    // Source maps roughly double the size of the executable
    if (!file.endsWith(".map")) {
      files.push(file.split("\\").join("/"));
    }
  }
  files.sort();
} else {
  console.warn(`No frontend build found at ${buildDir}, embedding nothing.`);
}

const importPath = (file: string) =>
  relative(outDir, join(buildDir, file)).split("\\").join("/");

const source = `// Generated by scripts/embed-frontend.ts. Do not edit.
// @ts-nocheck: TypeScript cannot type file imports
import type { AssetMap } from "../frontend";
${files
  .map(
    (file, i) =>
      `import asset${i} from ${JSON.stringify(importPath(file))} with { type: "file" };`
  )
  .join("\n")}

const assets: AssetMap = {
${files.map((file, i) => `  ${JSON.stringify(`/${file}`)}: asset${i},`).join("\n")}
};

export default assets;
`;

await mkdir(outDir, { recursive: true });
await Bun.write(outFile, source);
console.log(`Embedded ${files.length} frontend files in ${relative(backendDir, outFile)}`);
